import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

const CURATED_UNIVERSITIES = [
  {
    name: 'Stanford University',
    location: 'California',
    country: 'United States',
    rank: 3,
    tuition: 60000,
    acceptanceRate: '3.9%',
    matchScore: 0,
    tags: ['Dream', 'Top Tier', 'Tech Hub'],
    programs: ['Computer Science', 'Engineering', 'Business', 'Medicine'],
    description: 'A top-tier private research university known for its academic achievements, entrepreneurial culture, and proximity to Silicon Valley. Excels in technology, innovation, and interdisciplinary research.',
    risks: ['Extremely competitive admissions (under 4% acceptance)', 'High cost of living in Bay Area', 'Intense academic pressure'],
    strengths: ['World-class faculty and research facilities', 'Strong industry connections in tech', 'Generous financial aid for admitted students', 'Entrepreneurial ecosystem'],
    website: 'https://www.stanford.edu',
    domain: 'stanford.edu',
  },
  {
    name: 'Massachusetts Institute of Technology',
    location: 'Massachusetts',
    country: 'United States',
    rank: 1,
    tuition: 57986,
    acceptanceRate: '3.2%',
    matchScore: 0,
    tags: ['Dream', 'Top Tier', 'Engineering'],
    programs: ['Computer Science', 'Engineering', 'Physics', 'Mathematics'],
    description: 'World-leading institution in science, technology, and engineering. Known for cutting-edge research and innovation.',
    risks: ['Extremely selective', 'Rigorous workload', 'Cold weather'],
    strengths: ['Best STEM programs globally', 'Industry partnerships', 'Strong alumni network'],
    website: 'https://www.mit.edu',
    domain: 'mit.edu',
  },
  {
    name: 'Harvard University',
    location: 'Massachusetts',
    country: 'United States',
    rank: 4,
    tuition: 57261,
    acceptanceRate: '3.4%',
    matchScore: 0,
    tags: ['Dream', 'Top Tier', 'Ivy League'],
    programs: ['Law', 'Business', 'Medicine', 'Liberal Arts'],
    description: 'Oldest and most prestigious university in the United States with unmatched global reputation.',
    risks: ['Most competitive admissions', 'High expectations', 'Expensive location'],
    strengths: ['Best financial aid policies', 'World-class faculty', 'Unparalleled network'],
    website: 'https://www.harvard.edu',
    domain: 'harvard.edu',
  },
  {
    name: 'University of California, Berkeley',
    location: 'California',
    country: 'United States',
    rank: 10,
    tuition: 45000,
    acceptanceRate: '14.5%',
    matchScore: 0,
    tags: ['Target', 'Public Ivy', 'Research'],
    programs: ['Computer Science', 'Engineering', 'Business', 'Data Science'],
    description: 'Top public research university with world-class programs in engineering and sciences.',
    risks: ['Large class sizes', 'Competitive environment', 'Limited on-campus housing'],
    strengths: ['Affordable compared to private universities', 'Silicon Valley proximity', 'Diverse student body'],
    website: 'https://www.berkeley.edu',
    domain: 'berkeley.edu',
  },
  {
    name: 'University of Toronto',
    location: 'Ontario',
    country: 'Canada',
    rank: 21,
    tuition: 45000,
    acceptanceRate: '43%',
    matchScore: 0,
    tags: ['Target', 'Research Heavy', 'Diverse'],
    programs: ['Computer Science', 'Life Sciences', 'Engineering', 'Business'],
    description: "Canada's leading university with a global reputation for research and teaching excellence.",
    risks: ['Large class sizes', 'Cold winters', 'Competitive internal programs'],
    strengths: ['Post-study work permit (3 years)', 'Diverse international community', 'Affordable compared to US', 'High research output'],
    website: 'https://www.utoronto.ca',
    domain: 'utoronto.ca',
  },
  {
    name: 'Technical University of Munich',
    location: 'Munich',
    country: 'Germany',
    rank: 37,
    tuition: 0,
    acceptanceRate: '8%',
    matchScore: 0,
    tags: ['Target', 'Tech Focused', 'No Tuition'],
    programs: ['Engineering', 'Informatics', 'Physics', 'Management'],
    description: "One of Europe's top universities, excellent for engineering and technology with no tuition fees.",
    risks: ['German language required for many programs', 'Housing crisis in Munich', 'Bureaucratic processes'],
    strengths: ['No tuition fees', 'Strong engineering reputation', 'EU work opportunities', 'Industry connections'],
    website: 'https://www.tum.de',
    domain: 'tum.de',
  },
  {
    name: 'Imperial College London',
    location: 'London',
    country: 'United Kingdom',
    rank: 6,
    tuition: 50000,
    acceptanceRate: '14%',
    matchScore: 0,
    tags: ['Dream', 'Science Focus', 'Research'],
    programs: ['Medicine', 'Engineering', 'Business', 'Natural Sciences'],
    description: 'World-class university focusing exclusively on science, engineering, medicine, and business.',
    risks: ['Very high cost of living', 'Intensive workload', 'Expensive tuition for international students'],
    strengths: ['Prestigious degree', 'Central London location', 'Strong research focus', 'Excellent career outcomes'],
    website: 'https://www.imperial.ac.uk',
    domain: 'imperial.ac.uk',
  },
  {
    name: 'University of Melbourne',
    location: 'Melbourne',
    country: 'Australia',
    rank: 14,
    tuition: 35000,
    acceptanceRate: '70%',
    matchScore: 0,
    tags: ['Target', 'Global', 'Quality of Life'],
    programs: ['Arts', 'Commerce', 'Science', 'Engineering'],
    description: "Australia's number one university with strong global rankings.",
    risks: ['High cost of living', 'Distance from Europe/US', 'Visa restrictions'],
    strengths: ['Great lifestyle and weather', 'Post-study work visa (2-4 years)', 'Strong research output', 'Safe environment'],
    website: 'https://www.unimelb.edu.au',
    domain: 'unimelb.edu.au',
  },
  {
    name: 'National University of Singapore',
    location: 'Singapore',
    country: 'Singapore',
    rank: 8,
    tuition: 28000,
    acceptanceRate: '5%',
    matchScore: 0,
    tags: ['Dream', 'Asian Excellence', 'Business Hub'],
    programs: ['Computer Science', 'Engineering', 'Business', 'Life Sciences'],
    description: "Asia's leading university with world-class programs and global outlook.",
    risks: ['Very selective', 'Hot and humid climate', 'High cost of living'],
    strengths: ['Top Asian university', 'Business hub location', 'Strong job market', 'Multicultural environment'],
    website: 'https://www.nus.edu.sg',
    domain: 'nus.edu.sg',
  },
  {
    name: 'ETH Zurich',
    location: 'Zurich',
    country: 'Switzerland',
    rank: 7,
    tuition: 1500,
    acceptanceRate: '8%',
    matchScore: 0,
    tags: ['Dream', 'STEM Excellence', 'Low Cost'],
    programs: ['Engineering', 'Computer Science', 'Physics', 'Mathematics'],
    description: 'One of the world\'s leading universities for science and technology.',
    risks: ['Rigorous academic standards', 'High cost of living in Switzerland', 'Language barriers (German)'],
    strengths: ['Extremely low tuition', 'World-class STEM programs', 'Beautiful location', 'High quality of life'],
    website: 'https://ethz.ch',
    domain: 'ethz.ch',
  },
  {
    name: 'University of British Columbia',
    location: 'Vancouver',
    country: 'Canada',
    rank: 34,
    tuition: 42000,
    acceptanceRate: '52%',
    matchScore: 0,
    tags: ['Target', 'Beautiful Campus', 'Research'],
    programs: ['Computer Science', 'Engineering', 'Business', 'Environmental Science'],
    description: 'Major research university with stunning campus and strong academic programs.',
    risks: ['Rainy weather', 'Expensive city', 'Competitive programs'],
    strengths: ['Post-study work permit', 'Beautiful location', 'Strong research', 'Welcoming community'],
    website: 'https://www.ubc.ca',
    domain: 'ubc.ca',
  },
  {
    name: 'Arizona State University',
    location: 'Arizona',
    country: 'United States',
    rank: 216,
    tuition: 32000,
    acceptanceRate: '88%',
    matchScore: 0,
    tags: ['Safe', 'Innovation', 'Large University'],
    programs: ['Business', 'Engineering', 'Sustainability', 'Online Programs'],
    description: 'Known for innovation and accessibility with large student body.',
    risks: ['Very hot climate', 'Large class sizes', 'Party school reputation'],
    strengths: ['High acceptance rate', 'Good industry partnerships', 'Innovative programs', 'Affordable'],
    website: 'https://www.asu.edu',
    domain: 'asu.edu',
  },
];

export async function POST(request: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    // Delete existing universities
    await prisma.university.deleteMany();

    // Seed with curated data
    const universities = await prisma.university.createMany({
      data: CURATED_UNIVERSITIES,
    });

    return NextResponse.json({
      message: 'Universities seeded successfully',
      count: universities.count,
    });
  } catch (error) {
    console.error('Error seeding universities:', error);
    return NextResponse.json(
      { error: 'Failed to seed universities' },
      { status: 500 }
    );
  }
}
